local TableUIConfig = class("TableUIConfig")
TableUIConfig.TABLE_EXTENT_LENGTH = display.width - 920
TableUIConfig.TABLE_DESIGN_WIDTH = 880 + TableUIConfig.TABLE_EXTENT_LENGTH
TableUIConfig.TABLE_DESIGN_HEIGHT = 500
TableUIConfig.CARPET_CENTER = ccp(display.cx, display.cy)
TableUIConfig.TABLE_CENTER = ccp(display.cx, display.cy - 16)
TableUIConfig.TABLEINFO_CENTER = ccp(display.cx, display.cy)
TableUIConfig.LIGHT_SOURCE = ccp(display.cx, display.cy)
TableUIConfig.DEALER_CENTER = ccp(TableUIConfig.TABLE_CENTER.x, TableUIConfig.TABLE_CENTER.y + 240)
local tablePaddingLeft = (display.width - TableUIConfig.TABLE_DESIGN_WIDTH) * 0.5
local tablePaddingBottom = (display.height - TableUIConfig.TABLE_DESIGN_HEIGHT) * 0.5
TableUIConfig.SEAT = {}
TableUIConfig.SEAT[1] = ccp(0.7159090909090909 * TableUIConfig.TABLE_DESIGN_WIDTH + tablePaddingLeft, TableUIConfig.TABLE_DESIGN_HEIGHT + tablePaddingBottom - 16)
TableUIConfig.SEAT[2] = ccp(0.9306818181818182 * TableUIConfig.TABLE_DESIGN_WIDTH + tablePaddingLeft, 0.84 * TableUIConfig.TABLE_DESIGN_HEIGHT + tablePaddingBottom)
TableUIConfig.SEAT[3] = ccp(0.9511363636363637 * TableUIConfig.TABLE_DESIGN_WIDTH + tablePaddingLeft, 0.392 * TableUIConfig.TABLE_DESIGN_HEIGHT + tablePaddingBottom)
TableUIConfig.SEAT[4] = ccp(0.7727272727272727 * TableUIConfig.TABLE_DESIGN_WIDTH + tablePaddingLeft, 0.19 * TableUIConfig.TABLE_DESIGN_HEIGHT + tablePaddingBottom)
TableUIConfig.SEAT[5] = ccp(0.5113636363636364 * TableUIConfig.TABLE_DESIGN_WIDTH + tablePaddingLeft, 0.19 * TableUIConfig.TABLE_DESIGN_HEIGHT + tablePaddingBottom)
TableUIConfig.SEAT[6] = ccp(0.22727272727272727 * TableUIConfig.TABLE_DESIGN_WIDTH + tablePaddingLeft, 0.19 * TableUIConfig.TABLE_DESIGN_HEIGHT + tablePaddingBottom)
TableUIConfig.SEAT[7] = ccp(0.048863636363636366 * TableUIConfig.TABLE_DESIGN_WIDTH + tablePaddingLeft, 0.392 * TableUIConfig.TABLE_DESIGN_HEIGHT + tablePaddingBottom)
TableUIConfig.SEAT[8] = ccp(0.06931818181818182 * TableUIConfig.TABLE_DESIGN_WIDTH + tablePaddingLeft, 0.84 * TableUIConfig.TABLE_DESIGN_HEIGHT + tablePaddingBottom)
TableUIConfig.SEAT[9] = ccp(0.2840909090909091 * TableUIConfig.TABLE_DESIGN_WIDTH + tablePaddingLeft, TableUIConfig.TABLE_DESIGN_HEIGHT + tablePaddingBottom - 16)
local wagerPaddingLeft = (display.width - 720) * 0.5
TableUIConfig.WAGER_GAP = 4
TableUIConfig.WAGERVIEW = {}
TableUIConfig.WAGERVIEW[1] = ccp(TableUIConfig.SEAT[1].x, TableUIConfig.SEAT[1].y - 120)
TableUIConfig.WAGERVIEW[2] = ccp(TableUIConfig.SEAT[2].x - 110, TableUIConfig.SEAT[2].y - 80)
TableUIConfig.WAGERVIEW[3] = ccp(TableUIConfig.SEAT[3].x - 105, TableUIConfig.SEAT[3].y + 15)
TableUIConfig.WAGERVIEW[4] = ccp(TableUIConfig.SEAT[4].x - 60, TableUIConfig.SEAT[4].y + 120)
TableUIConfig.WAGERVIEW[5] = ccp(TableUIConfig.SEAT[5].x, TableUIConfig.SEAT[5].y + 120)
TableUIConfig.WAGERVIEW[6] = ccp(TableUIConfig.SEAT[6].x + 60, TableUIConfig.SEAT[6].y + 120)
TableUIConfig.WAGERVIEW[7] = ccp(TableUIConfig.SEAT[7].x + 105, TableUIConfig.SEAT[7].y + 15)
TableUIConfig.WAGERVIEW[8] = ccp(TableUIConfig.SEAT[8].x + 110, TableUIConfig.SEAT[8].y - 80)
TableUIConfig.WAGERVIEW[9] = ccp(TableUIConfig.SEAT[9].x, TableUIConfig.SEAT[9].y - 120)
TableUIConfig.COLLECT_CHIP_POINT = ccp(display.cx, display.cy + 80)
TableUIConfig.DEALER_MOVE_STEP_TIME = 0.3
TableUIConfig.DEALER_POKERS_CENTER = ccp(TableUIConfig.DEALER_CENTER.x, TableUIConfig.DEALER_CENTER.y - 115)
TableUIConfig.DEALER_OFFSET = ccp(0, -35)
TableUIConfig.STATICPOKER = {}
TableUIConfig.STATICPOKER[1] = ccp(TableUIConfig.SEAT[1].x - 75, TableUIConfig.SEAT[1].y - 70)
TableUIConfig.STATICPOKER[2] = ccp(TableUIConfig.SEAT[2].x - 100, TableUIConfig.SEAT[2].y - 25)
TableUIConfig.STATICPOKER[3] = ccp(TableUIConfig.SEAT[3].x - 75, TableUIConfig.SEAT[3].y + 95)
TableUIConfig.STATICPOKER[4] = ccp(TableUIConfig.SEAT[4].x + 70, TableUIConfig.SEAT[4].y + 50)
TableUIConfig.STATICPOKER[5] = ccp(TableUIConfig.SEAT[5].x - 90, TableUIConfig.SEAT[5].y + 30)
TableUIConfig.STATICPOKER[6] = ccp(TableUIConfig.SEAT[6].x - 70, TableUIConfig.SEAT[6].y + 50)
TableUIConfig.STATICPOKER[7] = ccp(TableUIConfig.SEAT[7].x + 75, TableUIConfig.SEAT[7].y + 95)
TableUIConfig.STATICPOKER[8] = ccp(TableUIConfig.SEAT[8].x + 100, TableUIConfig.SEAT[8].y - 25)
TableUIConfig.STATICPOKER[9] = ccp(TableUIConfig.SEAT[9].x + 75, TableUIConfig.SEAT[9].y - 70)
TableUIConfig.STATICPOKER[10] = ccp(TableUIConfig.DEALER_CENTER.x + 50, TableUIConfig.DEALER_CENTER.y - 85)
return TableUIConfig
