local PlayerConstants = {}
PlayerConstants.PlayerRole = {}
PlayerConstants.PlayerRole.VISITER = "PlayerRole.VISITER"
PlayerConstants.PlayerRole.GAMBLER = "PlayerRole.GAMBLER"
PlayerConstants.PlayerRole.BANKER = "PlayerRole.BANKER"
PlayerConstants.GamblerState = {}
PlayerConstants.GamblerState.UNSTART = "GamblerState.UNSTART"
PlayerConstants.GamblerState.START = "GamblerState.START"
PlayerConstants.GamblerState.UNBET = "GamblerState.UNBET"
PlayerConstants.GamblerState.BETTING = "GamblerState.BETTING"
PlayerConstants.GamblerState.BETTED = "GamblerState.BETTED"
PlayerConstants.GamblerState.WAITDISPATCH = "GamblerState.WAITDISPATCH"
PlayerConstants.GamblerState.DISPATCHING = "GamblerState.DISPATCHING"
PlayerConstants.GamblerState.DISPATCHED = "GamblerState.DISPATCHED"
PlayerConstants.GamblerState.POK = "GamblerState.POK"
PlayerConstants.GamblerState.VS = "GamblerState.VS"
PlayerConstants.GamblerState.WIN = "GamblerState.WIN"
PlayerConstants.GamblerState.LOST = "GamblerState.LOST"
PlayerConstants.GamblerState.EQUAL = "GamblerState.EQUAL"
PlayerConstants.GamblerState.FINISH = "GamblerState.FINISH"
return PlayerConstants
