// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ArenaStoreCfg.proto

#ifndef PROTOBUF_ArenaStoreCfg_2eproto__INCLUDED
#define PROTOBUF_ArenaStoreCfg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "ArenaDailyAwardCfg.pb.h"
// @@protoc_insertion_point(includes)

namespace com {
namespace cfg {
namespace vo {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ArenaStoreCfg_2eproto();
void protobuf_AssignDesc_ArenaStoreCfg_2eproto();
void protobuf_ShutdownFile_ArenaStoreCfg_2eproto();

class ArenaStoreCfg;
class ArenaStoreCfgSet;

// ===================================================================

class ArenaStoreCfg : public ::google::protobuf::MessageLite {
 public:
  ArenaStoreCfg();
  virtual ~ArenaStoreCfg();

  ArenaStoreCfg(const ArenaStoreCfg& from);

  inline ArenaStoreCfg& operator=(const ArenaStoreCfg& from) {
    CopyFrom(from);
    return *this;
  }

  static const ArenaStoreCfg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ArenaStoreCfg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ArenaStoreCfg* other);

  // implements Message ----------------------------------------------

  ArenaStoreCfg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ArenaStoreCfg& from);
  void MergeFrom(const ArenaStoreCfg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 Key = 1;
  inline bool has_key() const;
  inline void clear_key();
  static const int kKeyFieldNumber = 1;
  inline ::google::protobuf::uint32 key() const;
  inline void set_key(::google::protobuf::uint32 value);

  // required uint32 ArenaMoney = 2;
  inline bool has_arenamoney() const;
  inline void clear_arenamoney();
  static const int kArenaMoneyFieldNumber = 2;
  inline ::google::protobuf::uint32 arenamoney() const;
  inline void set_arenamoney(::google::protobuf::uint32 value);

  // required uint32 OpenLevel = 3;
  inline bool has_openlevel() const;
  inline void clear_openlevel();
  static const int kOpenLevelFieldNumber = 3;
  inline ::google::protobuf::uint32 openlevel() const;
  inline void set_openlevel(::google::protobuf::uint32 value);

  // required .com.cfg.vo.ArenaAwardElement AwardElmt = 4;
  inline bool has_awardelmt() const;
  inline void clear_awardelmt();
  static const int kAwardElmtFieldNumber = 4;
  inline const ::com::cfg::vo::ArenaAwardElement& awardelmt() const;
  inline ::com::cfg::vo::ArenaAwardElement* mutable_awardelmt();
  inline ::com::cfg::vo::ArenaAwardElement* release_awardelmt();
  inline void set_allocated_awardelmt(::com::cfg::vo::ArenaAwardElement* awardelmt);

  // @@protoc_insertion_point(class_scope:com.cfg.vo.ArenaStoreCfg)
 private:
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_arenamoney();
  inline void clear_has_arenamoney();
  inline void set_has_openlevel();
  inline void clear_has_openlevel();
  inline void set_has_awardelmt();
  inline void clear_has_awardelmt();

  ::google::protobuf::uint32 key_;
  ::google::protobuf::uint32 arenamoney_;
  ::com::cfg::vo::ArenaAwardElement* awardelmt_;
  ::google::protobuf::uint32 openlevel_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArenaStoreCfg_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArenaStoreCfg_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArenaStoreCfg_2eproto();
  friend void protobuf_ShutdownFile_ArenaStoreCfg_2eproto();

  void InitAsDefaultInstance();
  static ArenaStoreCfg* default_instance_;
};
// -------------------------------------------------------------------

class ArenaStoreCfgSet : public ::google::protobuf::MessageLite {
 public:
  ArenaStoreCfgSet();
  virtual ~ArenaStoreCfgSet();

  ArenaStoreCfgSet(const ArenaStoreCfgSet& from);

  inline ArenaStoreCfgSet& operator=(const ArenaStoreCfgSet& from) {
    CopyFrom(from);
    return *this;
  }

  static const ArenaStoreCfgSet& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ArenaStoreCfgSet* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ArenaStoreCfgSet* other);

  // implements Message ----------------------------------------------

  ArenaStoreCfgSet* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ArenaStoreCfgSet& from);
  void MergeFrom(const ArenaStoreCfgSet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .com.cfg.vo.ArenaStoreCfg arenaStoreCfg = 1;
  inline int arenastorecfg_size() const;
  inline void clear_arenastorecfg();
  static const int kArenaStoreCfgFieldNumber = 1;
  inline const ::com::cfg::vo::ArenaStoreCfg& arenastorecfg(int index) const;
  inline ::com::cfg::vo::ArenaStoreCfg* mutable_arenastorecfg(int index);
  inline ::com::cfg::vo::ArenaStoreCfg* add_arenastorecfg();
  inline const ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::ArenaStoreCfg >&
      arenastorecfg() const;
  inline ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::ArenaStoreCfg >*
      mutable_arenastorecfg();

  // @@protoc_insertion_point(class_scope:com.cfg.vo.ArenaStoreCfgSet)
 private:

  ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::ArenaStoreCfg > arenastorecfg_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ArenaStoreCfg_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ArenaStoreCfg_2eproto();
  #endif
  friend void protobuf_AssignDesc_ArenaStoreCfg_2eproto();
  friend void protobuf_ShutdownFile_ArenaStoreCfg_2eproto();

  void InitAsDefaultInstance();
  static ArenaStoreCfgSet* default_instance_;
};
// ===================================================================


// ===================================================================

// ArenaStoreCfg

// required uint32 Key = 1;
inline bool ArenaStoreCfg::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ArenaStoreCfg::set_has_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ArenaStoreCfg::clear_has_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ArenaStoreCfg::clear_key() {
  key_ = 0u;
  clear_has_key();
}
inline ::google::protobuf::uint32 ArenaStoreCfg::key() const {
  return key_;
}
inline void ArenaStoreCfg::set_key(::google::protobuf::uint32 value) {
  set_has_key();
  key_ = value;
}

// required uint32 ArenaMoney = 2;
inline bool ArenaStoreCfg::has_arenamoney() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ArenaStoreCfg::set_has_arenamoney() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ArenaStoreCfg::clear_has_arenamoney() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ArenaStoreCfg::clear_arenamoney() {
  arenamoney_ = 0u;
  clear_has_arenamoney();
}
inline ::google::protobuf::uint32 ArenaStoreCfg::arenamoney() const {
  return arenamoney_;
}
inline void ArenaStoreCfg::set_arenamoney(::google::protobuf::uint32 value) {
  set_has_arenamoney();
  arenamoney_ = value;
}

// required uint32 OpenLevel = 3;
inline bool ArenaStoreCfg::has_openlevel() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ArenaStoreCfg::set_has_openlevel() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ArenaStoreCfg::clear_has_openlevel() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ArenaStoreCfg::clear_openlevel() {
  openlevel_ = 0u;
  clear_has_openlevel();
}
inline ::google::protobuf::uint32 ArenaStoreCfg::openlevel() const {
  return openlevel_;
}
inline void ArenaStoreCfg::set_openlevel(::google::protobuf::uint32 value) {
  set_has_openlevel();
  openlevel_ = value;
}

// required .com.cfg.vo.ArenaAwardElement AwardElmt = 4;
inline bool ArenaStoreCfg::has_awardelmt() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ArenaStoreCfg::set_has_awardelmt() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ArenaStoreCfg::clear_has_awardelmt() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ArenaStoreCfg::clear_awardelmt() {
  if (awardelmt_ != NULL) awardelmt_->::com::cfg::vo::ArenaAwardElement::Clear();
  clear_has_awardelmt();
}
inline const ::com::cfg::vo::ArenaAwardElement& ArenaStoreCfg::awardelmt() const {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return awardelmt_ != NULL ? *awardelmt_ : *default_instance().awardelmt_;
#else
  return awardelmt_ != NULL ? *awardelmt_ : *default_instance_->awardelmt_;
#endif
}
inline ::com::cfg::vo::ArenaAwardElement* ArenaStoreCfg::mutable_awardelmt() {
  set_has_awardelmt();
  if (awardelmt_ == NULL) awardelmt_ = new ::com::cfg::vo::ArenaAwardElement;
  return awardelmt_;
}
inline ::com::cfg::vo::ArenaAwardElement* ArenaStoreCfg::release_awardelmt() {
  clear_has_awardelmt();
  ::com::cfg::vo::ArenaAwardElement* temp = awardelmt_;
  awardelmt_ = NULL;
  return temp;
}
inline void ArenaStoreCfg::set_allocated_awardelmt(::com::cfg::vo::ArenaAwardElement* awardelmt) {
  delete awardelmt_;
  awardelmt_ = awardelmt;
  if (awardelmt) {
    set_has_awardelmt();
  } else {
    clear_has_awardelmt();
  }
}

// -------------------------------------------------------------------

// ArenaStoreCfgSet

// repeated .com.cfg.vo.ArenaStoreCfg arenaStoreCfg = 1;
inline int ArenaStoreCfgSet::arenastorecfg_size() const {
  return arenastorecfg_.size();
}
inline void ArenaStoreCfgSet::clear_arenastorecfg() {
  arenastorecfg_.Clear();
}
inline const ::com::cfg::vo::ArenaStoreCfg& ArenaStoreCfgSet::arenastorecfg(int index) const {
  return arenastorecfg_.Get(index);
}
inline ::com::cfg::vo::ArenaStoreCfg* ArenaStoreCfgSet::mutable_arenastorecfg(int index) {
  return arenastorecfg_.Mutable(index);
}
inline ::com::cfg::vo::ArenaStoreCfg* ArenaStoreCfgSet::add_arenastorecfg() {
  return arenastorecfg_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::ArenaStoreCfg >&
ArenaStoreCfgSet::arenastorecfg() const {
  return arenastorecfg_;
}
inline ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::ArenaStoreCfg >*
ArenaStoreCfgSet::mutable_arenastorecfg() {
  return &arenastorecfg_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace vo
}  // namespace cfg
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ArenaStoreCfg_2eproto__INCLUDED
