// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BattleSysCfg.proto

#ifndef PROTOBUF_BattleSysCfg_2eproto__INCLUDED
#define PROTOBUF_BattleSysCfg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace cfg {
namespace vo {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_BattleSysCfg_2eproto();
void protobuf_AssignDesc_BattleSysCfg_2eproto();
void protobuf_ShutdownFile_BattleSysCfg_2eproto();

class BattleSysCfg;
class BattleSysCfgSet;

// ===================================================================

class BattleSysCfg : public ::google::protobuf::MessageLite {
 public:
  BattleSysCfg();
  virtual ~BattleSysCfg();

  BattleSysCfg(const BattleSysCfg& from);

  inline BattleSysCfg& operator=(const BattleSysCfg& from) {
    CopyFrom(from);
    return *this;
  }

  static const BattleSysCfg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const BattleSysCfg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(BattleSysCfg* other);

  // implements Message ----------------------------------------------

  BattleSysCfg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BattleSysCfg& from);
  void MergeFrom(const BattleSysCfg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 CfgID = 1;
  inline bool has_cfgid() const;
  inline void clear_cfgid();
  static const int kCfgIDFieldNumber = 1;
  inline ::google::protobuf::uint32 cfgid() const;
  inline void set_cfgid(::google::protobuf::uint32 value);

  // required uint32 TargetDefAdjust = 2;
  inline bool has_targetdefadjust() const;
  inline void clear_targetdefadjust();
  static const int kTargetDefAdjustFieldNumber = 2;
  inline ::google::protobuf::uint32 targetdefadjust() const;
  inline void set_targetdefadjust(::google::protobuf::uint32 value);

  // required uint32 DamageAdjustRatio = 3;
  inline bool has_damageadjustratio() const;
  inline void clear_damageadjustratio();
  static const int kDamageAdjustRatioFieldNumber = 3;
  inline ::google::protobuf::uint32 damageadjustratio() const;
  inline void set_damageadjustratio(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:com.cfg.vo.BattleSysCfg)
 private:
  inline void set_has_cfgid();
  inline void clear_has_cfgid();
  inline void set_has_targetdefadjust();
  inline void clear_has_targetdefadjust();
  inline void set_has_damageadjustratio();
  inline void clear_has_damageadjustratio();

  ::google::protobuf::uint32 cfgid_;
  ::google::protobuf::uint32 targetdefadjust_;
  ::google::protobuf::uint32 damageadjustratio_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_BattleSysCfg_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_BattleSysCfg_2eproto();
  #endif
  friend void protobuf_AssignDesc_BattleSysCfg_2eproto();
  friend void protobuf_ShutdownFile_BattleSysCfg_2eproto();

  void InitAsDefaultInstance();
  static BattleSysCfg* default_instance_;
};
// -------------------------------------------------------------------

class BattleSysCfgSet : public ::google::protobuf::MessageLite {
 public:
  BattleSysCfgSet();
  virtual ~BattleSysCfgSet();

  BattleSysCfgSet(const BattleSysCfgSet& from);

  inline BattleSysCfgSet& operator=(const BattleSysCfgSet& from) {
    CopyFrom(from);
    return *this;
  }

  static const BattleSysCfgSet& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const BattleSysCfgSet* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(BattleSysCfgSet* other);

  // implements Message ----------------------------------------------

  BattleSysCfgSet* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BattleSysCfgSet& from);
  void MergeFrom(const BattleSysCfgSet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .com.cfg.vo.BattleSysCfg BattleCfg = 1;
  inline int battlecfg_size() const;
  inline void clear_battlecfg();
  static const int kBattleCfgFieldNumber = 1;
  inline const ::com::cfg::vo::BattleSysCfg& battlecfg(int index) const;
  inline ::com::cfg::vo::BattleSysCfg* mutable_battlecfg(int index);
  inline ::com::cfg::vo::BattleSysCfg* add_battlecfg();
  inline const ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::BattleSysCfg >&
      battlecfg() const;
  inline ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::BattleSysCfg >*
      mutable_battlecfg();

  // @@protoc_insertion_point(class_scope:com.cfg.vo.BattleSysCfgSet)
 private:

  ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::BattleSysCfg > battlecfg_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_BattleSysCfg_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_BattleSysCfg_2eproto();
  #endif
  friend void protobuf_AssignDesc_BattleSysCfg_2eproto();
  friend void protobuf_ShutdownFile_BattleSysCfg_2eproto();

  void InitAsDefaultInstance();
  static BattleSysCfgSet* default_instance_;
};
// ===================================================================


// ===================================================================

// BattleSysCfg

// required uint32 CfgID = 1;
inline bool BattleSysCfg::has_cfgid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BattleSysCfg::set_has_cfgid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BattleSysCfg::clear_has_cfgid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BattleSysCfg::clear_cfgid() {
  cfgid_ = 0u;
  clear_has_cfgid();
}
inline ::google::protobuf::uint32 BattleSysCfg::cfgid() const {
  return cfgid_;
}
inline void BattleSysCfg::set_cfgid(::google::protobuf::uint32 value) {
  set_has_cfgid();
  cfgid_ = value;
}

// required uint32 TargetDefAdjust = 2;
inline bool BattleSysCfg::has_targetdefadjust() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BattleSysCfg::set_has_targetdefadjust() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BattleSysCfg::clear_has_targetdefadjust() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BattleSysCfg::clear_targetdefadjust() {
  targetdefadjust_ = 0u;
  clear_has_targetdefadjust();
}
inline ::google::protobuf::uint32 BattleSysCfg::targetdefadjust() const {
  return targetdefadjust_;
}
inline void BattleSysCfg::set_targetdefadjust(::google::protobuf::uint32 value) {
  set_has_targetdefadjust();
  targetdefadjust_ = value;
}

// required uint32 DamageAdjustRatio = 3;
inline bool BattleSysCfg::has_damageadjustratio() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BattleSysCfg::set_has_damageadjustratio() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BattleSysCfg::clear_has_damageadjustratio() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BattleSysCfg::clear_damageadjustratio() {
  damageadjustratio_ = 0u;
  clear_has_damageadjustratio();
}
inline ::google::protobuf::uint32 BattleSysCfg::damageadjustratio() const {
  return damageadjustratio_;
}
inline void BattleSysCfg::set_damageadjustratio(::google::protobuf::uint32 value) {
  set_has_damageadjustratio();
  damageadjustratio_ = value;
}

// -------------------------------------------------------------------

// BattleSysCfgSet

// repeated .com.cfg.vo.BattleSysCfg BattleCfg = 1;
inline int BattleSysCfgSet::battlecfg_size() const {
  return battlecfg_.size();
}
inline void BattleSysCfgSet::clear_battlecfg() {
  battlecfg_.Clear();
}
inline const ::com::cfg::vo::BattleSysCfg& BattleSysCfgSet::battlecfg(int index) const {
  return battlecfg_.Get(index);
}
inline ::com::cfg::vo::BattleSysCfg* BattleSysCfgSet::mutable_battlecfg(int index) {
  return battlecfg_.Mutable(index);
}
inline ::com::cfg::vo::BattleSysCfg* BattleSysCfgSet::add_battlecfg() {
  return battlecfg_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::BattleSysCfg >&
BattleSysCfgSet::battlecfg() const {
  return battlecfg_;
}
inline ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::BattleSysCfg >*
BattleSysCfgSet::mutable_battlecfg() {
  return &battlecfg_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace vo
}  // namespace cfg
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BattleSysCfg_2eproto__INCLUDED
