// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BattleDefRatioCfg.proto

#ifndef PROTOBUF_BattleDefRatioCfg_2eproto__INCLUDED
#define PROTOBUF_BattleDefRatioCfg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace cfg {
namespace vo {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_BattleDefRatioCfg_2eproto();
void protobuf_AssignDesc_BattleDefRatioCfg_2eproto();
void protobuf_ShutdownFile_BattleDefRatioCfg_2eproto();

class BattleDefRatioCfg;
class BattleDefRatioCfgSet;

// ===================================================================

class BattleDefRatioCfg : public ::google::protobuf::MessageLite {
 public:
  BattleDefRatioCfg();
  virtual ~BattleDefRatioCfg();

  BattleDefRatioCfg(const BattleDefRatioCfg& from);

  inline BattleDefRatioCfg& operator=(const BattleDefRatioCfg& from) {
    CopyFrom(from);
    return *this;
  }

  static const BattleDefRatioCfg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const BattleDefRatioCfg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(BattleDefRatioCfg* other);

  // implements Message ----------------------------------------------

  BattleDefRatioCfg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BattleDefRatioCfg& from);
  void MergeFrom(const BattleDefRatioCfg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 AtkType = 1;
  inline bool has_atktype() const;
  inline void clear_atktype();
  static const int kAtkTypeFieldNumber = 1;
  inline ::google::protobuf::uint32 atktype() const;
  inline void set_atktype(::google::protobuf::uint32 value);

  // required uint32 ArmorType = 2;
  inline bool has_armortype() const;
  inline void clear_armortype();
  static const int kArmorTypeFieldNumber = 2;
  inline ::google::protobuf::uint32 armortype() const;
  inline void set_armortype(::google::protobuf::uint32 value);

  // required uint32 DamageRatio = 4;
  inline bool has_damageratio() const;
  inline void clear_damageratio();
  static const int kDamageRatioFieldNumber = 4;
  inline ::google::protobuf::uint32 damageratio() const;
  inline void set_damageratio(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:com.cfg.vo.BattleDefRatioCfg)
 private:
  inline void set_has_atktype();
  inline void clear_has_atktype();
  inline void set_has_armortype();
  inline void clear_has_armortype();
  inline void set_has_damageratio();
  inline void clear_has_damageratio();

  ::google::protobuf::uint32 atktype_;
  ::google::protobuf::uint32 armortype_;
  ::google::protobuf::uint32 damageratio_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_BattleDefRatioCfg_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_BattleDefRatioCfg_2eproto();
  #endif
  friend void protobuf_AssignDesc_BattleDefRatioCfg_2eproto();
  friend void protobuf_ShutdownFile_BattleDefRatioCfg_2eproto();

  void InitAsDefaultInstance();
  static BattleDefRatioCfg* default_instance_;
};
// -------------------------------------------------------------------

class BattleDefRatioCfgSet : public ::google::protobuf::MessageLite {
 public:
  BattleDefRatioCfgSet();
  virtual ~BattleDefRatioCfgSet();

  BattleDefRatioCfgSet(const BattleDefRatioCfgSet& from);

  inline BattleDefRatioCfgSet& operator=(const BattleDefRatioCfgSet& from) {
    CopyFrom(from);
    return *this;
  }

  static const BattleDefRatioCfgSet& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const BattleDefRatioCfgSet* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(BattleDefRatioCfgSet* other);

  // implements Message ----------------------------------------------

  BattleDefRatioCfgSet* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BattleDefRatioCfgSet& from);
  void MergeFrom(const BattleDefRatioCfgSet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .com.cfg.vo.BattleDefRatioCfg BattleCfg = 1;
  inline int battlecfg_size() const;
  inline void clear_battlecfg();
  static const int kBattleCfgFieldNumber = 1;
  inline const ::com::cfg::vo::BattleDefRatioCfg& battlecfg(int index) const;
  inline ::com::cfg::vo::BattleDefRatioCfg* mutable_battlecfg(int index);
  inline ::com::cfg::vo::BattleDefRatioCfg* add_battlecfg();
  inline const ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::BattleDefRatioCfg >&
      battlecfg() const;
  inline ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::BattleDefRatioCfg >*
      mutable_battlecfg();

  // @@protoc_insertion_point(class_scope:com.cfg.vo.BattleDefRatioCfgSet)
 private:

  ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::BattleDefRatioCfg > battlecfg_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_BattleDefRatioCfg_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_BattleDefRatioCfg_2eproto();
  #endif
  friend void protobuf_AssignDesc_BattleDefRatioCfg_2eproto();
  friend void protobuf_ShutdownFile_BattleDefRatioCfg_2eproto();

  void InitAsDefaultInstance();
  static BattleDefRatioCfgSet* default_instance_;
};
// ===================================================================


// ===================================================================

// BattleDefRatioCfg

// required uint32 AtkType = 1;
inline bool BattleDefRatioCfg::has_atktype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BattleDefRatioCfg::set_has_atktype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BattleDefRatioCfg::clear_has_atktype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BattleDefRatioCfg::clear_atktype() {
  atktype_ = 0u;
  clear_has_atktype();
}
inline ::google::protobuf::uint32 BattleDefRatioCfg::atktype() const {
  return atktype_;
}
inline void BattleDefRatioCfg::set_atktype(::google::protobuf::uint32 value) {
  set_has_atktype();
  atktype_ = value;
}

// required uint32 ArmorType = 2;
inline bool BattleDefRatioCfg::has_armortype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BattleDefRatioCfg::set_has_armortype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BattleDefRatioCfg::clear_has_armortype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BattleDefRatioCfg::clear_armortype() {
  armortype_ = 0u;
  clear_has_armortype();
}
inline ::google::protobuf::uint32 BattleDefRatioCfg::armortype() const {
  return armortype_;
}
inline void BattleDefRatioCfg::set_armortype(::google::protobuf::uint32 value) {
  set_has_armortype();
  armortype_ = value;
}

// required uint32 DamageRatio = 4;
inline bool BattleDefRatioCfg::has_damageratio() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BattleDefRatioCfg::set_has_damageratio() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BattleDefRatioCfg::clear_has_damageratio() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BattleDefRatioCfg::clear_damageratio() {
  damageratio_ = 0u;
  clear_has_damageratio();
}
inline ::google::protobuf::uint32 BattleDefRatioCfg::damageratio() const {
  return damageratio_;
}
inline void BattleDefRatioCfg::set_damageratio(::google::protobuf::uint32 value) {
  set_has_damageratio();
  damageratio_ = value;
}

// -------------------------------------------------------------------

// BattleDefRatioCfgSet

// repeated .com.cfg.vo.BattleDefRatioCfg BattleCfg = 1;
inline int BattleDefRatioCfgSet::battlecfg_size() const {
  return battlecfg_.size();
}
inline void BattleDefRatioCfgSet::clear_battlecfg() {
  battlecfg_.Clear();
}
inline const ::com::cfg::vo::BattleDefRatioCfg& BattleDefRatioCfgSet::battlecfg(int index) const {
  return battlecfg_.Get(index);
}
inline ::com::cfg::vo::BattleDefRatioCfg* BattleDefRatioCfgSet::mutable_battlecfg(int index) {
  return battlecfg_.Mutable(index);
}
inline ::com::cfg::vo::BattleDefRatioCfg* BattleDefRatioCfgSet::add_battlecfg() {
  return battlecfg_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::BattleDefRatioCfg >&
BattleDefRatioCfgSet::battlecfg() const {
  return battlecfg_;
}
inline ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::BattleDefRatioCfg >*
BattleDefRatioCfgSet::mutable_battlecfg() {
  return &battlecfg_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace vo
}  // namespace cfg
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BattleDefRatioCfg_2eproto__INCLUDED
