// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EntryGroupCfg.proto

#ifndef PROTOBUF_EntryGroupCfg_2eproto__INCLUDED
#define PROTOBUF_EntryGroupCfg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace cfg {
namespace vo {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_EntryGroupCfg_2eproto();
void protobuf_AssignDesc_EntryGroupCfg_2eproto();
void protobuf_ShutdownFile_EntryGroupCfg_2eproto();

class EntryGroupCfg;
class EntryGroupCfgSet;

// ===================================================================

class EntryGroupCfg : public ::google::protobuf::MessageLite {
 public:
  EntryGroupCfg();
  virtual ~EntryGroupCfg();

  EntryGroupCfg(const EntryGroupCfg& from);

  inline EntryGroupCfg& operator=(const EntryGroupCfg& from) {
    CopyFrom(from);
    return *this;
  }

  static const EntryGroupCfg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const EntryGroupCfg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(EntryGroupCfg* other);

  // implements Message ----------------------------------------------

  EntryGroupCfg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const EntryGroupCfg& from);
  void MergeFrom(const EntryGroupCfg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 EntryGroupID = 1;
  inline bool has_entrygroupid() const;
  inline void clear_entrygroupid();
  static const int kEntryGroupIDFieldNumber = 1;
  inline ::google::protobuf::uint32 entrygroupid() const;
  inline void set_entrygroupid(::google::protobuf::uint32 value);

  // repeated uint32 EntryID = 2;
  inline int entryid_size() const;
  inline void clear_entryid();
  static const int kEntryIDFieldNumber = 2;
  inline ::google::protobuf::uint32 entryid(int index) const;
  inline void set_entryid(int index, ::google::protobuf::uint32 value);
  inline void add_entryid(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      entryid() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_entryid();

  // @@protoc_insertion_point(class_scope:com.cfg.vo.EntryGroupCfg)
 private:
  inline void set_has_entrygroupid();
  inline void clear_has_entrygroupid();

  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > entryid_;
  ::google::protobuf::uint32 entrygroupid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_EntryGroupCfg_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_EntryGroupCfg_2eproto();
  #endif
  friend void protobuf_AssignDesc_EntryGroupCfg_2eproto();
  friend void protobuf_ShutdownFile_EntryGroupCfg_2eproto();

  void InitAsDefaultInstance();
  static EntryGroupCfg* default_instance_;
};
// -------------------------------------------------------------------

class EntryGroupCfgSet : public ::google::protobuf::MessageLite {
 public:
  EntryGroupCfgSet();
  virtual ~EntryGroupCfgSet();

  EntryGroupCfgSet(const EntryGroupCfgSet& from);

  inline EntryGroupCfgSet& operator=(const EntryGroupCfgSet& from) {
    CopyFrom(from);
    return *this;
  }

  static const EntryGroupCfgSet& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const EntryGroupCfgSet* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(EntryGroupCfgSet* other);

  // implements Message ----------------------------------------------

  EntryGroupCfgSet* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const EntryGroupCfgSet& from);
  void MergeFrom(const EntryGroupCfgSet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .com.cfg.vo.EntryGroupCfg entrygroupcfg = 1;
  inline int entrygroupcfg_size() const;
  inline void clear_entrygroupcfg();
  static const int kEntrygroupcfgFieldNumber = 1;
  inline const ::com::cfg::vo::EntryGroupCfg& entrygroupcfg(int index) const;
  inline ::com::cfg::vo::EntryGroupCfg* mutable_entrygroupcfg(int index);
  inline ::com::cfg::vo::EntryGroupCfg* add_entrygroupcfg();
  inline const ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::EntryGroupCfg >&
      entrygroupcfg() const;
  inline ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::EntryGroupCfg >*
      mutable_entrygroupcfg();

  // @@protoc_insertion_point(class_scope:com.cfg.vo.EntryGroupCfgSet)
 private:

  ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::EntryGroupCfg > entrygroupcfg_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_EntryGroupCfg_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_EntryGroupCfg_2eproto();
  #endif
  friend void protobuf_AssignDesc_EntryGroupCfg_2eproto();
  friend void protobuf_ShutdownFile_EntryGroupCfg_2eproto();

  void InitAsDefaultInstance();
  static EntryGroupCfgSet* default_instance_;
};
// ===================================================================


// ===================================================================

// EntryGroupCfg

// required uint32 EntryGroupID = 1;
inline bool EntryGroupCfg::has_entrygroupid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EntryGroupCfg::set_has_entrygroupid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EntryGroupCfg::clear_has_entrygroupid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EntryGroupCfg::clear_entrygroupid() {
  entrygroupid_ = 0u;
  clear_has_entrygroupid();
}
inline ::google::protobuf::uint32 EntryGroupCfg::entrygroupid() const {
  return entrygroupid_;
}
inline void EntryGroupCfg::set_entrygroupid(::google::protobuf::uint32 value) {
  set_has_entrygroupid();
  entrygroupid_ = value;
}

// repeated uint32 EntryID = 2;
inline int EntryGroupCfg::entryid_size() const {
  return entryid_.size();
}
inline void EntryGroupCfg::clear_entryid() {
  entryid_.Clear();
}
inline ::google::protobuf::uint32 EntryGroupCfg::entryid(int index) const {
  return entryid_.Get(index);
}
inline void EntryGroupCfg::set_entryid(int index, ::google::protobuf::uint32 value) {
  entryid_.Set(index, value);
}
inline void EntryGroupCfg::add_entryid(::google::protobuf::uint32 value) {
  entryid_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
EntryGroupCfg::entryid() const {
  return entryid_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
EntryGroupCfg::mutable_entryid() {
  return &entryid_;
}

// -------------------------------------------------------------------

// EntryGroupCfgSet

// repeated .com.cfg.vo.EntryGroupCfg entrygroupcfg = 1;
inline int EntryGroupCfgSet::entrygroupcfg_size() const {
  return entrygroupcfg_.size();
}
inline void EntryGroupCfgSet::clear_entrygroupcfg() {
  entrygroupcfg_.Clear();
}
inline const ::com::cfg::vo::EntryGroupCfg& EntryGroupCfgSet::entrygroupcfg(int index) const {
  return entrygroupcfg_.Get(index);
}
inline ::com::cfg::vo::EntryGroupCfg* EntryGroupCfgSet::mutable_entrygroupcfg(int index) {
  return entrygroupcfg_.Mutable(index);
}
inline ::com::cfg::vo::EntryGroupCfg* EntryGroupCfgSet::add_entrygroupcfg() {
  return entrygroupcfg_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::EntryGroupCfg >&
EntryGroupCfgSet::entrygroupcfg() const {
  return entrygroupcfg_;
}
inline ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::EntryGroupCfg >*
EntryGroupCfgSet::mutable_entrygroupcfg() {
  return &entrygroupcfg_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace vo
}  // namespace cfg
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_EntryGroupCfg_2eproto__INCLUDED
