// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EvolutionSkillGrowCfg.proto

#ifndef PROTOBUF_EvolutionSkillGrowCfg_2eproto__INCLUDED
#define PROTOBUF_EvolutionSkillGrowCfg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace cfg {
namespace vo {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_EvolutionSkillGrowCfg_2eproto();
void protobuf_AssignDesc_EvolutionSkillGrowCfg_2eproto();
void protobuf_ShutdownFile_EvolutionSkillGrowCfg_2eproto();

class EvolutionSkillGrowCfg;
class EvolutionSkillGrowCfgSet;

// ===================================================================

class EvolutionSkillGrowCfg : public ::google::protobuf::MessageLite {
 public:
  EvolutionSkillGrowCfg();
  virtual ~EvolutionSkillGrowCfg();

  EvolutionSkillGrowCfg(const EvolutionSkillGrowCfg& from);

  inline EvolutionSkillGrowCfg& operator=(const EvolutionSkillGrowCfg& from) {
    CopyFrom(from);
    return *this;
  }

  static const EvolutionSkillGrowCfg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const EvolutionSkillGrowCfg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(EvolutionSkillGrowCfg* other);

  // implements Message ----------------------------------------------

  EvolutionSkillGrowCfg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const EvolutionSkillGrowCfg& from);
  void MergeFrom(const EvolutionSkillGrowCfg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 StartSkillID = 1;
  inline bool has_startskillid() const;
  inline void clear_startskillid();
  static const int kStartSkillIDFieldNumber = 1;
  inline ::google::protobuf::uint32 startskillid() const;
  inline void set_startskillid(::google::protobuf::uint32 value);

  // required uint32 GrowMulti = 2;
  inline bool has_growmulti() const;
  inline void clear_growmulti();
  static const int kGrowMultiFieldNumber = 2;
  inline ::google::protobuf::uint32 growmulti() const;
  inline void set_growmulti(::google::protobuf::uint32 value);

  // repeated uint32 SkillIDs = 3;
  inline int skillids_size() const;
  inline void clear_skillids();
  static const int kSkillIDsFieldNumber = 3;
  inline ::google::protobuf::uint32 skillids(int index) const;
  inline void set_skillids(int index, ::google::protobuf::uint32 value);
  inline void add_skillids(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      skillids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_skillids();

  // @@protoc_insertion_point(class_scope:com.cfg.vo.EvolutionSkillGrowCfg)
 private:
  inline void set_has_startskillid();
  inline void clear_has_startskillid();
  inline void set_has_growmulti();
  inline void clear_has_growmulti();

  ::google::protobuf::uint32 startskillid_;
  ::google::protobuf::uint32 growmulti_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > skillids_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_EvolutionSkillGrowCfg_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_EvolutionSkillGrowCfg_2eproto();
  #endif
  friend void protobuf_AssignDesc_EvolutionSkillGrowCfg_2eproto();
  friend void protobuf_ShutdownFile_EvolutionSkillGrowCfg_2eproto();

  void InitAsDefaultInstance();
  static EvolutionSkillGrowCfg* default_instance_;
};
// -------------------------------------------------------------------

class EvolutionSkillGrowCfgSet : public ::google::protobuf::MessageLite {
 public:
  EvolutionSkillGrowCfgSet();
  virtual ~EvolutionSkillGrowCfgSet();

  EvolutionSkillGrowCfgSet(const EvolutionSkillGrowCfgSet& from);

  inline EvolutionSkillGrowCfgSet& operator=(const EvolutionSkillGrowCfgSet& from) {
    CopyFrom(from);
    return *this;
  }

  static const EvolutionSkillGrowCfgSet& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const EvolutionSkillGrowCfgSet* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(EvolutionSkillGrowCfgSet* other);

  // implements Message ----------------------------------------------

  EvolutionSkillGrowCfgSet* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const EvolutionSkillGrowCfgSet& from);
  void MergeFrom(const EvolutionSkillGrowCfgSet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .com.cfg.vo.EvolutionSkillGrowCfg evolutionskillgrowcfg = 1;
  inline int evolutionskillgrowcfg_size() const;
  inline void clear_evolutionskillgrowcfg();
  static const int kEvolutionskillgrowcfgFieldNumber = 1;
  inline const ::com::cfg::vo::EvolutionSkillGrowCfg& evolutionskillgrowcfg(int index) const;
  inline ::com::cfg::vo::EvolutionSkillGrowCfg* mutable_evolutionskillgrowcfg(int index);
  inline ::com::cfg::vo::EvolutionSkillGrowCfg* add_evolutionskillgrowcfg();
  inline const ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::EvolutionSkillGrowCfg >&
      evolutionskillgrowcfg() const;
  inline ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::EvolutionSkillGrowCfg >*
      mutable_evolutionskillgrowcfg();

  // @@protoc_insertion_point(class_scope:com.cfg.vo.EvolutionSkillGrowCfgSet)
 private:

  ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::EvolutionSkillGrowCfg > evolutionskillgrowcfg_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_EvolutionSkillGrowCfg_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_EvolutionSkillGrowCfg_2eproto();
  #endif
  friend void protobuf_AssignDesc_EvolutionSkillGrowCfg_2eproto();
  friend void protobuf_ShutdownFile_EvolutionSkillGrowCfg_2eproto();

  void InitAsDefaultInstance();
  static EvolutionSkillGrowCfgSet* default_instance_;
};
// ===================================================================


// ===================================================================

// EvolutionSkillGrowCfg

// required uint32 StartSkillID = 1;
inline bool EvolutionSkillGrowCfg::has_startskillid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EvolutionSkillGrowCfg::set_has_startskillid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EvolutionSkillGrowCfg::clear_has_startskillid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EvolutionSkillGrowCfg::clear_startskillid() {
  startskillid_ = 0u;
  clear_has_startskillid();
}
inline ::google::protobuf::uint32 EvolutionSkillGrowCfg::startskillid() const {
  return startskillid_;
}
inline void EvolutionSkillGrowCfg::set_startskillid(::google::protobuf::uint32 value) {
  set_has_startskillid();
  startskillid_ = value;
}

// required uint32 GrowMulti = 2;
inline bool EvolutionSkillGrowCfg::has_growmulti() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EvolutionSkillGrowCfg::set_has_growmulti() {
  _has_bits_[0] |= 0x00000002u;
}
inline void EvolutionSkillGrowCfg::clear_has_growmulti() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void EvolutionSkillGrowCfg::clear_growmulti() {
  growmulti_ = 0u;
  clear_has_growmulti();
}
inline ::google::protobuf::uint32 EvolutionSkillGrowCfg::growmulti() const {
  return growmulti_;
}
inline void EvolutionSkillGrowCfg::set_growmulti(::google::protobuf::uint32 value) {
  set_has_growmulti();
  growmulti_ = value;
}

// repeated uint32 SkillIDs = 3;
inline int EvolutionSkillGrowCfg::skillids_size() const {
  return skillids_.size();
}
inline void EvolutionSkillGrowCfg::clear_skillids() {
  skillids_.Clear();
}
inline ::google::protobuf::uint32 EvolutionSkillGrowCfg::skillids(int index) const {
  return skillids_.Get(index);
}
inline void EvolutionSkillGrowCfg::set_skillids(int index, ::google::protobuf::uint32 value) {
  skillids_.Set(index, value);
}
inline void EvolutionSkillGrowCfg::add_skillids(::google::protobuf::uint32 value) {
  skillids_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
EvolutionSkillGrowCfg::skillids() const {
  return skillids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
EvolutionSkillGrowCfg::mutable_skillids() {
  return &skillids_;
}

// -------------------------------------------------------------------

// EvolutionSkillGrowCfgSet

// repeated .com.cfg.vo.EvolutionSkillGrowCfg evolutionskillgrowcfg = 1;
inline int EvolutionSkillGrowCfgSet::evolutionskillgrowcfg_size() const {
  return evolutionskillgrowcfg_.size();
}
inline void EvolutionSkillGrowCfgSet::clear_evolutionskillgrowcfg() {
  evolutionskillgrowcfg_.Clear();
}
inline const ::com::cfg::vo::EvolutionSkillGrowCfg& EvolutionSkillGrowCfgSet::evolutionskillgrowcfg(int index) const {
  return evolutionskillgrowcfg_.Get(index);
}
inline ::com::cfg::vo::EvolutionSkillGrowCfg* EvolutionSkillGrowCfgSet::mutable_evolutionskillgrowcfg(int index) {
  return evolutionskillgrowcfg_.Mutable(index);
}
inline ::com::cfg::vo::EvolutionSkillGrowCfg* EvolutionSkillGrowCfgSet::add_evolutionskillgrowcfg() {
  return evolutionskillgrowcfg_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::EvolutionSkillGrowCfg >&
EvolutionSkillGrowCfgSet::evolutionskillgrowcfg() const {
  return evolutionskillgrowcfg_;
}
inline ::google::protobuf::RepeatedPtrField< ::com::cfg::vo::EvolutionSkillGrowCfg >*
EvolutionSkillGrowCfgSet::mutable_evolutionskillgrowcfg() {
  return &evolutionskillgrowcfg_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace vo
}  // namespace cfg
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_EvolutionSkillGrowCfg_2eproto__INCLUDED
