// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GenStrengthenCfg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GenStrengthenCfg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace cfg {
namespace vo {

void protobuf_ShutdownFile_GenStrengthenCfg_2eproto() {
  delete GenStrengthenCfg::default_instance_;
  delete GenStrengthenCfgSet::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_GenStrengthenCfg_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_GenStrengthenCfg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  GenStrengthenCfg::default_instance_ = new GenStrengthenCfg();
  GenStrengthenCfgSet::default_instance_ = new GenStrengthenCfgSet();
  GenStrengthenCfg::default_instance_->InitAsDefaultInstance();
  GenStrengthenCfgSet::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_GenStrengthenCfg_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_GenStrengthenCfg_2eproto_once_);
void protobuf_AddDesc_GenStrengthenCfg_2eproto() {
  ::google::protobuf::::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_GenStrengthenCfg_2eproto_once_,
                 &protobuf_AddDesc_GenStrengthenCfg_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_GenStrengthenCfg_2eproto {
  StaticDescriptorInitializer_GenStrengthenCfg_2eproto() {
    protobuf_AddDesc_GenStrengthenCfg_2eproto();
  }
} static_descriptor_initializer_GenStrengthenCfg_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int GenStrengthenCfg::kIDFieldNumber;
const int GenStrengthenCfg::kCostCoinFieldNumber;
const int GenStrengthenCfg::kNameFieldNumber;
const int GenStrengthenCfg::kDescFieldNumber;
const int GenStrengthenCfg::kIconFieldNumber;
#endif  // !_MSC_VER

GenStrengthenCfg::GenStrengthenCfg()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void GenStrengthenCfg::InitAsDefaultInstance() {
}

GenStrengthenCfg::GenStrengthenCfg(const GenStrengthenCfg& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void GenStrengthenCfg::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0u;
  costcoin_ = 0u;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  icon_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GenStrengthenCfg::~GenStrengthenCfg() {
  SharedDtor();
}

void GenStrengthenCfg::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (desc_ != &::google::protobuf::internal::kEmptyString) {
    delete desc_;
  }
  if (icon_ != &::google::protobuf::internal::kEmptyString) {
    delete icon_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void GenStrengthenCfg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const GenStrengthenCfg& GenStrengthenCfg::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_GenStrengthenCfg_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_GenStrengthenCfg_2eproto();
#endif
  return *default_instance_;
}

GenStrengthenCfg* GenStrengthenCfg::default_instance_ = NULL;

GenStrengthenCfg* GenStrengthenCfg::New() const {
  return new GenStrengthenCfg;
}

void GenStrengthenCfg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0u;
    costcoin_ = 0u;
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    if (has_desc()) {
      if (desc_ != &::google::protobuf::internal::kEmptyString) {
        desc_->clear();
      }
    }
    if (has_icon()) {
      if (icon_ != &::google::protobuf::internal::kEmptyString) {
        icon_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool GenStrengthenCfg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 ID = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_CostCoin;
        break;
      }

      // required uint32 CostCoin = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_CostCoin:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &costcoin_)));
          set_has_costcoin();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_Name;
        break;
      }

      // required string Name = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_Name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_Desc;
        break;
      }

      // required string Desc = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_Desc:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_desc()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_Icon;
        break;
      }

      // required string Icon = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_Icon:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_icon()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void GenStrengthenCfg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 ID = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // required uint32 CostCoin = 2;
  if (has_costcoin()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->costcoin(), output);
  }

  // required string Name = 3;
  if (has_name()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->name(), output);
  }

  // required string Desc = 4;
  if (has_desc()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->desc(), output);
  }

  // required string Icon = 5;
  if (has_icon()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->icon(), output);
  }

}

int GenStrengthenCfg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 ID = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->id());
    }

    // required uint32 CostCoin = 2;
    if (has_costcoin()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->costcoin());
    }

    // required string Name = 3;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // required string Desc = 4;
    if (has_desc()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->desc());
    }

    // required string Icon = 5;
    if (has_icon()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->icon());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GenStrengthenCfg::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const GenStrengthenCfg*>(&from));
}

void GenStrengthenCfg::MergeFrom(const GenStrengthenCfg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_costcoin()) {
      set_costcoin(from.costcoin());
    }
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_desc()) {
      set_desc(from.desc());
    }
    if (from.has_icon()) {
      set_icon(from.icon());
    }
  }
}

void GenStrengthenCfg::CopyFrom(const GenStrengthenCfg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GenStrengthenCfg::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000001f) != 0x0000001f) return false;

  return true;
}

void GenStrengthenCfg::Swap(GenStrengthenCfg* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(costcoin_, other->costcoin_);
    std::swap(name_, other->name_);
    std::swap(desc_, other->desc_);
    std::swap(icon_, other->icon_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string GenStrengthenCfg::GetTypeName() const {
  return "com.cfg.vo.GenStrengthenCfg";
}


// ===================================================================

#ifndef _MSC_VER
const int GenStrengthenCfgSet::kGenstrengthencfgFieldNumber;
#endif  // !_MSC_VER

GenStrengthenCfgSet::GenStrengthenCfgSet()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void GenStrengthenCfgSet::InitAsDefaultInstance() {
}

GenStrengthenCfgSet::GenStrengthenCfgSet(const GenStrengthenCfgSet& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void GenStrengthenCfgSet::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GenStrengthenCfgSet::~GenStrengthenCfgSet() {
  SharedDtor();
}

void GenStrengthenCfgSet::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void GenStrengthenCfgSet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const GenStrengthenCfgSet& GenStrengthenCfgSet::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_GenStrengthenCfg_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_GenStrengthenCfg_2eproto();
#endif
  return *default_instance_;
}

GenStrengthenCfgSet* GenStrengthenCfgSet::default_instance_ = NULL;

GenStrengthenCfgSet* GenStrengthenCfgSet::New() const {
  return new GenStrengthenCfgSet;
}

void GenStrengthenCfgSet::Clear() {
  genstrengthencfg_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool GenStrengthenCfgSet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .com.cfg.vo.GenStrengthenCfg genstrengthencfg = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_genstrengthencfg:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_genstrengthencfg()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_genstrengthencfg;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void GenStrengthenCfgSet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .com.cfg.vo.GenStrengthenCfg genstrengthencfg = 1;
  for (int i = 0; i < this->genstrengthencfg_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->genstrengthencfg(i), output);
  }

}

int GenStrengthenCfgSet::ByteSize() const {
  int total_size = 0;

  // repeated .com.cfg.vo.GenStrengthenCfg genstrengthencfg = 1;
  total_size += 1 * this->genstrengthencfg_size();
  for (int i = 0; i < this->genstrengthencfg_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->genstrengthencfg(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GenStrengthenCfgSet::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const GenStrengthenCfgSet*>(&from));
}

void GenStrengthenCfgSet::MergeFrom(const GenStrengthenCfgSet& from) {
  GOOGLE_CHECK_NE(&from, this);
  genstrengthencfg_.MergeFrom(from.genstrengthencfg_);
}

void GenStrengthenCfgSet::CopyFrom(const GenStrengthenCfgSet& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GenStrengthenCfgSet::IsInitialized() const {

  for (int i = 0; i < genstrengthencfg_size(); i++) {
    if (!this->genstrengthencfg(i).IsInitialized()) return false;
  }
  return true;
}

void GenStrengthenCfgSet::Swap(GenStrengthenCfgSet* other) {
  if (other != this) {
    genstrengthencfg_.Swap(&other->genstrengthencfg_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string GenStrengthenCfgSet::GetTypeName() const {
  return "com.cfg.vo.GenStrengthenCfgSet";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace vo
}  // namespace cfg
}  // namespace com

// @@protoc_insertion_point(global_scope)
