// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CSPushMsg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CSPushMsg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace vmsg {

void protobuf_ShutdownFile_CSPushMsg_2eproto() {
  delete CSUMemDeviceTokenReport::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_CSPushMsg_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_CSPushMsg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ::vmsg::protobuf_AddDesc_MsgBase_2eproto();
  ::vmsg::protobuf_AddDesc_ShareByClient_2eproto();
  ::vmsg::protobuf_AddDesc_CSBagMsg_2eproto();
  CSUMemDeviceTokenReport::default_instance_ = new CSUMemDeviceTokenReport();
  CSUMemDeviceTokenReport::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CSPushMsg_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_CSPushMsg_2eproto_once_);
void protobuf_AddDesc_CSPushMsg_2eproto() {
  ::google::protobuf::::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_CSPushMsg_2eproto_once_,
                 &protobuf_AddDesc_CSPushMsg_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CSPushMsg_2eproto {
  StaticDescriptorInitializer_CSPushMsg_2eproto() {
    protobuf_AddDesc_CSPushMsg_2eproto();
  }
} static_descriptor_initializer_CSPushMsg_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int CSUMemDeviceTokenReport::kTokenFieldNumber;
#endif  // !_MSC_VER

CSUMemDeviceTokenReport::CSUMemDeviceTokenReport()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void CSUMemDeviceTokenReport::InitAsDefaultInstance() {
}

CSUMemDeviceTokenReport::CSUMemDeviceTokenReport(const CSUMemDeviceTokenReport& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void CSUMemDeviceTokenReport::SharedCtor() {
  _cached_size_ = 0;
  token_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CSUMemDeviceTokenReport::~CSUMemDeviceTokenReport() {
  SharedDtor();
}

void CSUMemDeviceTokenReport::SharedDtor() {
  if (token_ != &::google::protobuf::internal::kEmptyString) {
    delete token_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void CSUMemDeviceTokenReport::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const CSUMemDeviceTokenReport& CSUMemDeviceTokenReport::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_CSPushMsg_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_CSPushMsg_2eproto();
#endif
  return *default_instance_;
}

CSUMemDeviceTokenReport* CSUMemDeviceTokenReport::default_instance_ = NULL;

CSUMemDeviceTokenReport* CSUMemDeviceTokenReport::New() const {
  return new CSUMemDeviceTokenReport;
}

void CSUMemDeviceTokenReport::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_token()) {
      if (token_ != &::google::protobuf::internal::kEmptyString) {
        token_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool CSUMemDeviceTokenReport::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string Token = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_token()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CSUMemDeviceTokenReport::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string Token = 1;
  if (has_token()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->token(), output);
  }

}

int CSUMemDeviceTokenReport::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string Token = 1;
    if (has_token()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->token());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CSUMemDeviceTokenReport::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const CSUMemDeviceTokenReport*>(&from));
}

void CSUMemDeviceTokenReport::MergeFrom(const CSUMemDeviceTokenReport& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_token()) {
      set_token(from.token());
    }
  }
}

void CSUMemDeviceTokenReport::CopyFrom(const CSUMemDeviceTokenReport& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CSUMemDeviceTokenReport::IsInitialized() const {

  return true;
}

void CSUMemDeviceTokenReport::Swap(CSUMemDeviceTokenReport* other) {
  if (other != this) {
    std::swap(token_, other->token_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string CSUMemDeviceTokenReport::GetTypeName() const {
  return "vmsg.CSUMemDeviceTokenReport";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace vmsg

// @@protoc_insertion_point(global_scope)
