
#include "stdafx.h"

#include "GamePackets.h"
#include "HP.pb.h"


#ifndef _REGISISTER_FACTORIES_
#define _REGISISTER_FACTORIES_

AUTO_REGISITER_PACKET_FACTORY(HPLogin,LOGIN_C);
AUTO_REGISITER_PACKET_FACTORY(HPLoginRet,LOGIN_S);




AUTO_REGISITER_PACKET_FACTORY(HPHeartBeat,HEART_BEAT);
AUTO_REGISITER_PACKET_FACTORY(HPRoleCreateRet,ROLE_CREATE_S);


//登录之后服务器同步过来初始数据
AUTO_REGISITER_PACKET_FACTORY(HPPlayerInfoSync,PLAYER_INFO_SYNC_S);
AUTO_REGISITER_PACKET_FACTORY(HPRoleInfoSync,ROLE_INFO_SYNC_S);
//AUTO_REGISITER_PACKET_FACTORY(HPPlayerStateSync,STATE_INFO_SYNC_S);
AUTO_REGISITER_PACKET_FACTORY(HPItemInfoSync,ITEM_INFO_SYNC_S);
AUTO_REGISITER_PACKET_FACTORY(HPEquipInfoSync,EQUIP_INFO_SYNC_S);
AUTO_REGISITER_PACKET_FACTORY(HPSkillInfoSync,SKILL_INFO_SYNC_S);
AUTO_REGISITER_PACKET_FACTORY(HPAssembleFinish,ASSEMBLE_FINISH_S);
//获奖统一接口
AUTO_REGISITER_PACKET_FACTORY(HPPlayerReward,PLAYER_AWARD_S);
//消耗统一接口
AUTO_REGISITER_PACKET_FACTORY(HPConsumeInfo,PLAYER_CONSUME_S);

//服务器传来的错误信息
AUTO_REGISITER_PACKET_FACTORY(HPErrorCode, ERROR_CODE);
//静默重启服务器
AUTO_REGISITER_PACKET_FACTORY(HPPlayerKickout, PLAYER_KICKOUT_S);

#endif//_REGISISTER_FACTORIES_